FROM node:18-alpine

WORKDIR /app

# Installer les dépendances
COPY package*.json ./
RUN npm install

# Exposer le port de développement React
EXPOSE 3000

# Variable d'environnement pour l'API
ENV REACT_APP_API_URL=http://localhost:8050

# Commande par défaut : démarrer le serveur de développement
CMD ["npm", "start"]






